In [5]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sklearn
from sklearn.preprocessing import OrdinalEncoder

In [14]:
import pandas as pd
data = pd.read_csv('housing_data_08-02-2021.csv', index_col=0)
data.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57,4,4,52000
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52,4,5,56000
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42,4,4,37000
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65,1,4,49500
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70,3,5,55000

In [18]:
data['district'].value_counts().index

Index(['Чиланзарский', 'Мирзо-Улугбекский', 'Юнусабадский', 'Учтепинский',
       'Мирабадский', 'Яккасарайский', 'Яшнободский', 'Шайхантахурский',
       'Олмазорский', 'Сергелийский', 'Янгихаётский', 'Бектемирский'],
      dtype='object')

In [12]:
def clean_data(df):
    df.drop('location',axis=1,inplace=True)
    ordinal = OrdinalEncoder()
    joylashuv_category_encoded = ordinal.fit_transform(df[['district']])
    df.drop('district',axis=1,inplace=True)
    df['new_district'] = pd.DataFrame(joylashuv_category_encoded)
    df['price'] = df['price'].str.replace('Договорная', '0')
    df['price'] = df['price'].fillna(method='bfill')
    df['price'] = df['price'].astype(int)
    return df
data = clean_data(data)

In [13]:
data

      rooms size  level  max_levels  price  new_district
0         3   57      4           4  52000           8.0
1         2   52      4           5  56000           9.0
2         2   42      4           4  37000           6.0
3         3   65      1           4  49500           6.0
4         3   70      3           5  55000           6.0
...     ...  ...    ...         ...    ...           ...
7560      1   38      5           5  24500          11.0
7561      2   49      1           4  32000          11.0
7562      2   64      3           9  40000           7.0
7563      1   18      1           4  11000           2.0
7564      1   30      2           4  22914           6.0

[7565 rows x 6 columns]

In [ ]:
data['']