In [7]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import sklearn
from sklearn.preprocessing import OneHotEncoder

In [8]:
import pandas as pd
data = pd.read_csv('housing_data_08-02-2021.csv', index_col=0)
data.head()

,location,district,rooms,size,level,max_levels,price
0,"город Ташкент, Юнусабадский район, Юнусабад 8-...",Юнусабадский,3,57,4,4,52000
1,"город Ташкент, Яккасарайский район, 1-й тупик ...",Яккасарайский,2,52,4,5,56000
2,"город Ташкент, Чиланзарский район, Чиланзар 2-...",Чиланзарский,2,42,4,4,37000
3,"город Ташкент, Чиланзарский район, Чиланзар 9-...",Чиланзарский,3,65,1,4,49500
4,"город Ташкент, Чиланзарский район, площадь Актепа",Чиланзарский,3,70,3,5,55000

In [9]:
data['location'].value_counts()

город Ташкент, Чиланзарский район, Чиланзар                112
город Ташкент, Яккасарайский район, Кушбеги                110
город Ташкент, Мирзо-Улугбекский район, Буюк Ипак Йули      87
город Ташкент, Яккасарайский район, Бабура                  82
город Ташкент, Учтепинский район, Чиланзар 24-й квартал     79
                                                          ...
город Ташкент, Юнусабадский район, 8-й проезд Янгишахар      1
город Ташкент, Учтепинский район, 1-й проезд Козигузар       1
город Ташкент, Чиланзарский район, Яккабог                   1
город Ташкент, Олмазорский район, Каракамыш2/4               1
город Ташкент, Яшнободский район, Базар Кадышева             1
Name: location, Length: 1600, dtype: int64

In [10]:
def clean_data(df):
    df.drop('location',axis=1,inplace=True)
    joylashuv_category_encoded = pd.get_dummies(df['district'])
    df.drop('district',axis=1,inplace=True)
    df['price'] = df['price'].str.replace('Договорная', '0')
    df['price'] = df['price'].fillna(method='bfill')
    df['price'] = df['price'].astype(int)
    df['size'] = df['size'].str.replace('Площадьземли:1сот', '0').astype(float)
    return np.c_[df, joylashuv_category_encoded]
data = clean_data(data)

In [11]:
column = ['rooms','size','level','max_levels','price', 'Чиланзарский', 'Мирзо-Улугбекский', 'Юнусабадский', 'Учтепинский',
       'Мирабадский', 'Яккасарайский', 'Яшнободский', 'Шайхантахурский',
       'Олмазорский', 'Сергелийский', 'Янгихаётский', 'Бектемирский']
new_data = pd.DataFrame(data, columns=column)

In [12]:
new_data

,rooms,size,level,max_levels,price,Чиланзарский,Мирзо-Улугбекский,Юнусабадский,Учтепинский,Мирабадский,Яккасарайский,Яшнободский,Шайхантахурский,Олмазорский,Сергелийский,Янгихаётский,Бектемирский
0,3.0,57.0,4.0,4.0,52000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,2.0,52.0,4.0,5.0,56000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2.0,42.0,4.0,4.0,37000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,3.0,65.0,1.0,4.0,49500.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,3.0,70.0,3.0,5.0,55000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7560,1.0,38.0,5.0,5.0,24500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7561,2.0,49.0,1.0,4.0,32000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7562,2.0,64.0,3.0,9.0,40000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7563,1.0,18.0,1.0,4.0,11000.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7564,1.0,30.0,2.0,4.0,22914.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [13]:
new_data.corrwith(new_data['price'])

rooms                0.055357
size                 0.001125
level               -0.003707
max_levels           0.010459
price                1.000000
Чиланзарский        -0.002093
Мирзо-Улугбекский    0.014105
Юнусабадский        -0.010472
Учтепинский         -0.001464
Мирабадский         -0.007425
Яккасарайский        0.018857
Яшнободский         -0.015059
Шайхантахурский      0.012491
Олмазорский         -0.001055
Сергелийский        -0.000945
Янгихаётский        -0.002548
Бектемирский        -0.002738
dtype: float64

In [14]:
from sklearn.model_selection import train_test_split    
train_set, test_set = train_test_split(new_data, test_size=0.2, random_state=0)

X_train = train_set.drop('price', axis=1)
y_train = train_set['price'].copy()
X_test = test_set.drop('price', axis=1)
y_test = test_set['price'].copy()

In [15]:
from sklearn.svm import SVC 

LR_model = SVC()

In [68]:
LR_model.fit(X_train, y_train)

SVC()

In [69]:
LR_model.score(X_test,y_test)

0.019167217448777262

In [64]:
from sklearn.linear_model import LogisticRegression

logistik = LogisticRegression()
logistik.fit(X_train,y_train)

/Users/azamatergashev/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [65]:
logistik.score(X_test,y_test)

0.019167217448777262

In [128]:
x = clean_data_2.drop("price",axis=1)
y = clean_data_2["price"]

X_train,x_test,Y_train,y_test = train_test_split(x,y, test_size=0.2)

In [129]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
# clf = make_pipeline(StandardScaler())
clf.fit(X_train, Y_train)

/Users/azamatergashev/anaconda3/envs/tensorflow/lib/python3.10/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

LinearSVC()

In [130]:
clf.score(x_test,y_test)*100

0.0

In [131]:
clean_data_2.isnull().sum()

rooms         0
size          0
level         0
max_levels    0
price         0
dtype: int64

In [133]:
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor()
sgd.fit(X_train, Y_train)

SGDRegressor()

In [134]:
sgd.score(x_test,y_test)

-2.1412751861990035e+17